# Generated by Django 5.0.4 on 2024-04-19 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_names', models.CharField(max_length=300)),
                ('room_type', models.CharField(max_length=25)),
                ('availability', models.IntegerField()),
                ('hotels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.hotellocation')),
            ],
        ),
    ]
