# Generated by Django 5.0.4 on 2024-04-19 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='hotels',
            new_name='hotel_location',
        ),
    ]
