# Generated by Django 5.0.4 on 2024-04-20 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_hotels_hotels_hotel_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='room_type',
        ),
    ]
