# Generated by Django 5.0.4 on 2024-05-09 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_booking_rename_user_address_users_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user_phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.users'),
        ),
    ]
